version: "3.9"

services:
  app:
    container_name: app
    build:
      args:
        - BASE_IMAGE=pytorch/pytorch
        - BASE_IMAGE_TAG=2.0.0-cuda11.7-cudnn8-devel
        - PYTHON_VERSION=3.9
      context: app
      dockerfile: Dockerfile
      target: run
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]