version: "3.9"
services:
  app:
    container_name: app-dev
    build:
      target: ${TARGET_STAGE:-dev}
    ports:
      - "8080:80"
    command: sleep infinity
    volumes:
      - .:/workspace:cached