version: "3.9"
services:
  app:
    container_name: app-dev
    build:
      args:
        - PYTHON_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/python
      target: ${TARGET_STAGE:-dev}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8080:80"
    command: sleep infinity
    volumes:
      - .:/workspace:cached